apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-networking
  namespace: flux-system
spec:
  interval: 5m0s
  path: ../../infrastructure/networking/overlays/dev
  prune: true
  targetNamespace: metallb-system
  healthChecks:
    - kind: HelmRelease
      name: metallb
      namespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: flux-system
