apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- infra-monitoring-kustomization.yaml
- infra-networking-kustomization.yaml
- infra-networking-config-kustomization.yaml
- infra-istio-kustomization.yaml
