apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository-istio.yaml
  - helmrelease-istio-base.yaml
  - helmrelease-istiod.yaml
  - helmrelease-istio-ingressgateway.yaml
