apiVersion: v1
kind: Secret
metadata:
    name: monitoring-values-secret
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:w8PToBQa+YU0nYX93sMQ6AeiknOpT7PsoSUPhLkT0BDfzqHUAlmx3+EAHq7YR7wqMBXOyHrEFKesWryJ6WxINYhRcC0kPe9khrdYjmYUxea5+47F,iv:J/kHnnUNeoWAgJwX6wticpiCxaWr5kjBwA1+o1DeQBQ=,tag:n6EtDsGqZu41f//V36BQAQ==,type:str]
sops:
    age:
        - recipient: age1ujvf242nyq5v0fsjtcam889x46jqwp6mnj7uqtl2kntpt6xeyu0st2dy2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWXFWWHFsZWphSVI0Nmw4
            TmkxTkIzTGNlL0V3djZZNU1pODM2U1ZsTjJBCkJWQ3hodzQ5L3l3M0Z3R3dUdmo0
            dDV4ZSthNzRQRUZPcGNySllBWWRHNDAKLS0tIGJYUVRnOFhkNnpQais5dmVLZHVF
            ajNWRXF4cStSd0FybEJCOHFWdzQ0UDQKZEBUCUhVLrFroA4iRRzQBZ72+WO5NF8S
            5B4CwWuZk0S7PPYkl4MELdFG2lhjM+3UcxOXuz4yBRTeFBgvOZCy/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T03:05:10Z"
    mac: ENC[AES256_GCM,data:kDfk0bNJ59ida4OPVQyCIePSsvIEwjGFK+Hri8kDvUYnPnVxohYpEqlyNMseSFOU120mPum4PFxnONCgswkayX2QecDE1TVtYYxFIpukx/vN69cJnGTl1ErnxyDp0mZozNQ3MysnjjRCuoX3irHQ0ieSgxMqAUS8V7HQDGnbvdE=,iv:Sc8c9U27A92L9hWHk044UuzKOPYOjw7CsyoiZ2GKe0A=,tag:ozWWj8psQnLukXbPxoZ1kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
